(setq-default c-basic-offset 4)
(global-set-key "\M-j" 'backward-word)
(global-set-key "\M-J" 'backward-kill-word)
(global-set-key "\M-k" 'forward-word)
(global-set-key "\M-K" 'kill-word)
(global-set-key "\C-c\C-r" 'rgrep)
(global-set-key "\C-cu" 'uncomment-region)
(global-set-key (kbd "C-<f12>") 'enlarge-window-horizontally)
(global-set-key (kbd "C-<f11>") 'shrink-window-horizontally)
(global-set-key (kbd "C-<f10>") 'enlarge-window)
(global-set-key (kbd "C-<f9>") 'shrink-window)
(global-set-key (kbd "\C-cc") 'comment-or-uncomment-region)
(global-set-key (kbd "\C-h") 'delete-backward-char)
(global-set-key (kbd "\C-cm") 'menu-bar-open)
(global-set-key (kbd "\C-xh") 'help)
(global-set-key (kbd "\C-ce")     (lambda()(interactive)(find-file "~/.emacs"))) ; open .emacs
(global-set-key (kbd "\C-cb")     (lambda()(interactive)(find-file "~/.bashrc"))) ; open .bashrc
(require 'paren) (show-paren-mode t)